### Makefile -- Marqueur constant pour les termes des listes

# Author: Michael Grünewald
# Date: Lun 16 oct 2006 08:22:38 CEST

# Copyright (C) 2006-2014 Michael Grünewald
# All rights reserved.
#
# This file is part of Cadet TeX.
#
# Cadet TeX is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cadet TeX is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cadet TeX.  If not, see <http://www.gnu.org/licenses/>.


PACKAGE = itemmark

LOCALE = kobaia.tex
LOCALE+= de.tex
LOCALE+= en.tex
LOCALE+= en_US.tex
LOCALE+= fr.tex

.include "cadet.files.mk"

### End of file `Makefile'
