### Makefile

# Author: Michael Grünewald
# Date: Fri Apr  4 12:41:17 CEST 2014

# Copyright (C) 2014 Michael Grünewald
# All rights reserved.
#
# This file is part of Bhrìd TeX.
#
# Bhrìd TeX is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bhrìd TeX is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bhrìd TeX.  If not, see <http://www.gnu.org/licenses/>.


DOCS+= encoding.tex
DOCS+= case.tex
DOCS+= write.tex

test: test.sh all
	sh ./test.sh

.include "bhrid.project.mk"

### End of file `Makefile'
