### Makefile

# Cadet TeX (https://github.com/foretspaisibles/cadet)
# This file is part of Cadet TeX.
#
# Copyright © 2001–2021 Michaël Le Barbier
# All rights reserved.

# This software is governed by the CeCILL-B license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-B
# license as circulated by CEA, CNRS and INRIA at the following URL
# "https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt"



DOCUMENT=		galley.tex

SRCS+=			galley.tex
SRCS+=			gsssr.tex
SRCS+=			local.mac
SRCS+=			agraf.tex
SRCS+=			appbor.tex
SRCS+=			gsssr.tex
SRCS+=			radjsl2.tex
SRCS+=			rsm2sl2.tex
SRCS+=			rstdsl2.tex
SRCS+=			torcn.tex
SRCS+=			torrep.tex
SRCS+=			torsg.tex

CLEANFILES+=		galley.aux

.include "cadet.project.mk"

### End of file `Makefile'
