### Makefile

# Author: Michael Grünewald
# Date: Lun 16 oct 2006 08:22:38 CEST
# Copyright: (C) 2006, 2013 Michael Grünewald

# Copyright (C) 2006, 2013 Michael Grünewald
# All rights reserved.
#
# This file is part of Bhrìd TeX.
#
# Bhrìd TeX is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bhrìd TeX is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bhrìd TeX.  If not, see <http://www.gnu.org/licenses/>.


DOCS+= verbatim.tex
DOCS+= zapfd.tex
DOCS+= boxes.tex

.include "bhrid.project.mk"

### End of file `Makefile'
